image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - dart-code.flutter@3.20.0:fCUgJ2byoDmsmQf0Dq12+g==
    - dart-code.dart-code@3.20.1:gKwMOzlkrgxrb7aPrMdQ8w==