image:
  file: .devcontainer/Dockerfile

tasks:
  - init: flutter pub get

ports:
  - port: 9100
    onOpen: ignore

vscode:
  extensions:
    - editorconfig.editorconfig
    - dart-code.dart-code
    - dart-code.flutter
