image:
  file: .gitpod.Dockerfile

# tasks:

ports:
  - port: 9100
    onOpen: ignore

vscode:
  extensions:
    - dart-code.flutter@3.20.0:fCUgJ2byoDmsmQf0Dq12+g==
    - dart-code.dart-code@3.20.1:gKwMOzlkrgxrb7aPrMdQ8w==
